---
- name: check if docker is installed
  shell:
    which docker
  register: _hasdocker
  changed_when: no
  check_mode: no
  ignore_errors: yes
  tags:
    - docker

- name: ensure dependencies are installed (apt)
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "software-properties-common"
    - "python-pip"
    - "linux-image-extra-{{ ansible_kernel }}"
  when: ansible_os_family == "Debian"
  become: yes
  tags:
    - docker
    - packages
    - apt

- name: ensure dependencies are installed (yum)
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "python-pip"
  when: ansible_os_family == "RedHat"
  become: yes
  tags:
    - docker
    - packages
    - apt

- name: get docker installer and run
  shell: >
    curl https://releases.rancher.com/install-docker/{{ docker_version }}.sh | sh
  become: yes
  when: _hasdocker.rc != 0
  tags:
    - docker

# - name: 'Install docker-py'
  # pip:
    # name: docker-py
    # version: "{{ docker_py_version | default(omit) }}"
    # state: present
  # become: yes
  # tags:
    # - docker
    # - pip
    # - python

- name: ensure docker is started and enabled
  service:
    name: docker
    enabled: yes
    state: started
  become: yes
  tags:
    - docker
    - service

- name: configure overlay2
  template:
    backup: yes
    src: etc-docker-daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: '0755'
    owner: root
    group: root
  become: yes
  tags:
    - docker
  notify:
    - restart docker
    # - stop docker
    # - start docker

# vim:ft=ansible:
