---
- name: restart docker
  service:
    name: docker
    state: restarted
  become: yes

- name: stop docker
  service:
    name: docker
    state: stopped
  become: yes

- name: start docker
  service:
    name: docker
    state: started
  become: yes
# vim:ft=ansible:
